// ts-cli/src/solid/components/SessionPicker.tsx
/**
 * SessionPicker — session history list with search, resume, delete.
 * Ported from Ink/React to Solid/OpenTUI.
 */
import { createMemo, createSignal } from "solid-js"
import { useTheme } from "../context/theme"
import { useKeyboard } from "@opentui/solid"

export interface SessionInfo {
  id: string
  title: string
  createdAt: string
  updatedAt?: string
  messageCount: number
}

interface Props {
  sessions: SessionInfo[]
  onSelect: (session: SessionInfo | null) => void
  onDelete?: (sessionId: string) => void
}

const MAX_SHOW = 10

export function SessionPicker(props: Props) {
  const { theme } = useTheme()
  const [selected, setSelected] = createSignal(0)
  const [scrollOffset, setScrollOffset] = createSignal(0)
  const [filter, setFilter] = createSignal("")

  const visible = createMemo(() => {
    const f = filter().toLowerCase()
    if (!f) return props.sessions
    return props.sessions.filter((s) =>
      s.title.toLowerCase().includes(f) || s.id.toLowerCase().includes(f),
    )
  })

  const sliced = createMemo(() => {
    const so = scrollOffset()
    return visible().slice(so, so + MAX_SHOW)
  })

  useKeyboard((evt: any) => {
    const key = evt || {}
    const keyName = key.name ?? ""
    const input = key.sequence ?? ""

    if (keyName === "escape") { props.onSelect(null); return }
    if (keyName === "down") { setSelected((p) => Math.min(p + 1, visible().length - 1)); return }
    if (keyName === "up") { setSelected((p) => Math.max(p - 1, 0)); return }
    if (keyName === "pagedown") { setSelected((p) => Math.min(p + MAX_SHOW, visible().length - 1)); return }
    if (keyName === "pageup") { setSelected((p) => Math.max(p - MAX_SHOW, 0)); return }
    if (keyName === "home") { setSelected(0); return }
    if (keyName === "end") { setSelected(visible().length - 1); return }
    if (keyName === "enter" || keyName === "return") {
      const v = visible()
      const s = selected()
      if (v.length > 0 && s >= 0 && s < v.length) {
        props.onSelect(v[s])
      }
      return
    }
    if ((keyName === "delete" || keyName === "backspace") && !key.ctrl) {
      setFilter((p) => p.slice(0, -1))
      return
    }
    if (keyName === "delete" && props.onDelete && visible().length > 0) {
      const s = selected()
      if (s >= 0 && s < visible().length) {
        props.onDelete(visible()[s].id)
      }
      return
    }
    // Filter by typing
    if (!key.ctrl && !key.meta && input && input.length === 1 && keyName !== "enter") {
      setFilter((p) => p + input)
      return
    }
  })

  const formatDate = (iso: string) => {
    try {
      const d = new Date(iso)
      return d.toLocaleDateString() + " " + d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
    } catch { return iso }
  }

  return (
    <box flexDirection="column" paddingX={1} width={66}>
      <box>
        <text fg={theme.primary} attributes={1}>Session History</text>
        <text fg={theme.textMuted}>  type to filter / Enter resume / Del delete / Esc close</text>
      </box>
      {filter() && (
        <box paddingLeft={1}>
          <text fg={theme.textMuted}>Filter: </text>
          <text fg={theme.warning}>{filter()}</text>
        </box>
      )}
      {sliced().length === 0 && (
        <box paddingLeft={2}><text fg={theme.textMuted}>No sessions found.</text></box>
      )}
      {sliced().map((s, i) => {
        const idx = scrollOffset() + i
        return (
          <box key={s.id} paddingLeft={1}>
            <text fg={idx === selected() ? theme.primary : undefined} attributes={idx === selected() ? 1 : 0}>
              {idx === selected() ? "> " : "  "}
            </text>
            <text fg={theme.success}>{s.id}</text>
            <text fg={theme.textMuted}>  {s.title.slice(0, 30)}</text>
            <text fg={theme.textMuted}>  [{s.messageCount} msgs]</text>
            <text fg={theme.textMuted}>  {formatDate(s.updatedAt || s.createdAt)}</text>
          </box>
        )
      })}
      {visible().length > MAX_SHOW && (
        <box>
          <text fg={theme.textMuted}>
            {"  "}{scrollOffset() + 1}-{Math.min(scrollOffset() + MAX_SHOW, visible().length)} / {visible().length}
          </text>
        </box>
      )}
    </box>
  )
}

// ts-cli/src/components/SessionPicker.tsx
/**
 * SessionPicker — session history list with search, resume, delete.
 */
import { useState, useMemo, useEffect } from 'react';
import { Box, Text, useInput, useStdout } from 'ink';
import { t } from '../theme.js';

export interface SessionInfo {
  id: string;
  title: string;
  createdAt: string;
  updatedAt?: string;
  messageCount: number;
}

interface Props {
  sessions: SessionInfo[];
  onSelect: (session: SessionInfo | null) => void;
  onDelete?: (sessionId: string) => void;
}

export function SessionPicker({ sessions, onSelect, onDelete }: Props) {
  const [selected, setSelected] = useState(0);
  const [scrollOffset, setScrollOffset] = useState(0);
  const [filter, setFilter] = useState('');
  const { stdout } = useStdout();
  const terminalRows = (stdout as NodeJS.WriteStream)?.rows || 24;

  const visible = useMemo(() => {
    const f = filter.toLowerCase();
    if (!f) return sessions;
    return sessions.filter(s =>
      s.title.toLowerCase().includes(f) || s.id.toLowerCase().includes(f),
    );
  }, [sessions, filter]);

  useEffect(() => { setSelected(0); setScrollOffset(0); }, [filter]);

  const maxShow = Math.max(5, Math.min(terminalRows - 12, 10));

  useEffect(() => {
    setScrollOffset(prev => {
      if (selected < prev) return selected;
      if (selected >= prev + maxShow) return selected - maxShow + 1;
      return prev;
    });
  }, [selected, maxShow]);

  const sliced = visible.slice(scrollOffset, scrollOffset + maxShow);

  useInput((_input, key) => {
    if (key.escape) { onSelect(null); return; }
    if (key.downArrow) { setSelected(prev => Math.min(prev + 1, visible.length - 1)); return; }
    if (key.upArrow) { setSelected(prev => Math.max(prev - 1, 0)); return; }
    if (key.pageDown) { setSelected(prev => Math.min(prev + maxShow, visible.length - 1)); return; }
    if (key.pageUp) { setSelected(prev => Math.max(prev - maxShow, 0)); return; }
    if (key.return) {
      if (visible.length > 0 && selected >= 0 && selected < visible.length) {
        onSelect(visible[selected]);
      }
    }
    if (key.delete && onDelete && visible.length > 0 && selected >= 0 && selected < visible.length) {
      onDelete(visible[selected].id);
    }
    // Filter by typing
    if (!key.ctrl && !key.meta && _input && _input.length === 1 && !key.return && !key.escape) {
      setFilter(prev => prev + _input);
    }
    if (key.backspace || key.delete) {
      setFilter(prev => prev.slice(0, -1));
    }
  });

  const formatDate = (iso: string) => {
    try {
      const d = new Date(iso);
      return d.toLocaleDateString() + ' ' + d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    } catch { return iso; }
  };

  return (
    <Box flexDirection="column" borderStyle="single" borderColor={t.primary} paddingX={1} width={66}>
      <Box>
        <Text bold color={t.primary}>Session History</Text>
        <Text dimColor>  type to filter / Enter resume / Del delete / Esc close</Text>
      </Box>
      {filter && (
        <Box paddingLeft={1}>
          <Text dimColor>Filter: </Text>
          <Text color={t.warning}>{filter}</Text>
        </Box>
      )}
      {sliced.length === 0 && (
        <Box paddingLeft={2}><Text dimColor>No sessions found.</Text></Box>
      )}
      {sliced.map((s, i) => {
        const idx = scrollOffset + i;
        return (
          <Box key={s.id} paddingLeft={1}>
            <Text color={idx === selected ? t.primary : undefined} bold={idx === selected}>
              {idx === selected ? '> ' : '  '}
            </Text>
            <Text color={t.success}>{s.id}</Text>
            <Text dimColor>  {s.title.slice(0, 30)}</Text>
            <Text color={t.muted}>  [{s.messageCount} msgs]</Text>
            <Text dimColor>  {formatDate(s.updatedAt || s.createdAt)}</Text>
          </Box>
        );
      })}
      {visible.length > maxShow && (
        <Box><Text dimColor>  {scrollOffset + 1}-{Math.min(scrollOffset + maxShow, visible.length)} / {visible.length}</Text></Box>
      )}
    </Box>
  );
}
