// ts-cli/src/solid/components/StatusLine.tsx
/**
 * StatusLine — single-line compact status bar with optional secondary row.
 *
 * Row 1: jwcode [Plan] ● model  Nmsgs  tokens+tok=total  ███░ 80%  12.5t/s  30s  status text
 * Row 2: [DEGRADED] ...  or  ⚙ compaction ...  (only when active)
 */
import { createSignal, createMemo, onCleanup, onMount } from "solid-js"
import { useTheme } from "../context/theme"
import { useAppStateContext } from "../hooks/AppStateProvider"
import { RGBA } from "@opentui/core"

function formatTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1_000) return `${Math.round(n / 1_000)}K`
  return String(n)
}

function formatRate(rate: number): string {
  if (rate <= 0) return ""
  if (rate >= 100) return `${Math.round(rate)}t/s`
  return `${rate.toFixed(1)}t/s`
}

function formatElapsed(sec: number): string {
  if (sec <= 0) return ""
  if (sec >= 60) {
    const m = Math.floor(sec / 60)
    const s = sec % 60
    return `${m}m${s}s`
  }
  return `${sec}s`
}

function soften(c: RGBA, factor = 0.85): RGBA {
  const gray = 0.299 * c.r + 0.587 * c.g + 0.114 * c.b
  return RGBA.fromValues(
    gray + (c.r - gray) * factor,
    gray + (c.g - gray) * factor,
    gray + (c.b - gray) * factor,
    c.a,
  )
}

function dimColor(c: RGBA): RGBA {
  return RGBA.fromValues(c.r * 0.6, c.g * 0.6, c.b * 0.6, c.a)
}

interface StatusLineProps {
  selectionActive?: boolean
  selectionChars?: number
  selectedText?: string
}

export function StatusLine(props?: StatusLineProps) {
  const { theme: colors } = useTheme()
  const {
    usage, modelName, planMode, autoMode, connected, statusText,
    messages, tokenRate, isGenerating,
    degradation, planTasks, pdcaPhase, compactionProgress,
    scrollOffset,
  } = useAppStateContext()

  // ── Elapsed timer ──
  let startTime = 0
  const [elapsed, setElapsed] = createSignal(0)
  let interval: ReturnType<typeof setInterval> | undefined

  onMount(() => {
    if (isGenerating() && startTime === 0) startTime = Date.now()
  })

  interval = setInterval(() => {
    const gen = isGenerating()
    if (gen) {
      if (startTime === 0) startTime = Date.now()
      setElapsed(Math.floor((Date.now() - startTime) / 1000))
    } else {
      startTime = 0
      if (elapsed() > 0) setElapsed(0)
    }
  }, 1000)

  onCleanup(() => {
    if (interval) clearInterval(interval)
  })

  // ── Memoized color transforms (avoid RGBA alloc per tick) ──
  const brandColor = createMemo(() => soften(colors.primary, 0.88))
  const successFg = createMemo(() => soften(colors.success, 0.88))
  const warningFg = createMemo(() => soften(colors.warning, 0.80))
  const errorFg = createMemo(() => soften(colors.error, 0.75))
  const muted = createMemo(() => dimColor(colors.textMuted))
  const dimText = createMemo(() => dimColor(colors.text))

  // ── Computed values ──
  const pct = () => Math.min(100, Math.round(usage().usageRatio * 100))
  const filled = () => Math.round(pct() / 10)
  const bar = () => "█".repeat(filled()) + "░".repeat(10 - filled())
  const model = () => modelName() || (connected() ? "ready" : "connecting...")
  const connIcon = () => (connected() ? "●" : "○")
  const rateStr = () => formatRate(tokenRate())
  const elapsedStr = () => formatElapsed(elapsed())
  const p = () => usage().promptTokens
  const c = () => usage().completionTokens
  const totalMsgs = () => messages().length
  const hasScrolled = () => scrollOffset() > 0
  const scrollLabel = () => `↑${scrollOffset()}`

  // Status text — truncated early so it fits inline
  const statusDisplay = createMemo(() => {
    const st = statusText()
    if (!st || st === "connecting...") return ""
    return st.slice(0, 50)
  })

  const isStatusError = () => statusText().startsWith("Error:")

  // Whether secondary info (degradation / compaction) needs a second row
  const showSecondary = () => degradation().active || compactionProgress() !== null

  return (
    <box flexDirection="column" width="100%">
      {/* ── Row 1: status text early, token bar/time at the end ── */}
      <box height={1}>
        <text fg={brandColor()}>jwcode</text>
        <text fg={muted()}> </text>

        {hasScrolled() && (
          <>
            <text fg={colors.warning}>{scrollLabel()}</text>
            <text fg={muted()}> </text>
          </>
        )}

        <text
          bg={planMode() ? colors.secondary : colors.success}
          fg={RGBA.fromInts(0, 0, 0)}
        >
          {planMode() ? " Plan" : " Act"}
        </text>

        {autoMode() && (
          <text bg={colors.warning} fg={RGBA.fromInts(0, 0, 0)}> AUTO</text>
        )}

        {pdcaPhase() && (
          <>
            <text bg={colors.warning} fg={RGBA.fromInts(0, 0, 0)}> {pdcaPhase()}</text>
            {planTasks().length > 0 && (
              <>
                <text fg={muted()}> </text>
                <text fg={colors.primary}>
                  {planTasks().filter((t) => t.status === "completed").length}
                </text>
                <text fg={muted()}>/</text>
                <text fg={colors.text}>{planTasks().length}</text>
              </>
            )}
          </>
        )}

        <text fg={connected() ? colors.success : colors.error}>{connIcon()}</text>
        <text fg={successFg()}>{model()}</text>
        <text fg={muted()}> </text>

        {totalMsgs() > 0 && (
          <>
            <text fg={colors.text}>{totalMsgs()}</text>
            <text fg={muted()}>msgs </text>
          </>
        )}

        {props?.selectionActive && !!props?.selectionChars && (
          <>
            <text fg={colors.info}>sel{props.selectionChars}</text>
            <text fg={muted()}> </text>
          </>
        )}

        {/* Status text early */}
        {statusDisplay() && (
          <text
            fg={isStatusError() ? colors.error : dimText()}
            attributes={isStatusError() ? 1 : 0}
          >
            {statusDisplay()}
          </text>
        )}

        {/* Token/time bar compacted at the end */}
        <text fg={muted()}> </text>
        <text>{formatTokens(p())}</text>
        <text fg={muted()}>+</text>
        <text fg={successFg()}>{formatTokens(c())}</text>
        <text fg={muted()}>=</text>
        <text fg={warningFg()}>{formatTokens(usage().totalTokens)}</text>
        <text fg={muted()}> </text>
        <text
          fg={
            pct() > 90 ? errorFg() : pct() > 70 ? warningFg() : colors.text
          }
        >
          {bar()} {pct()}%
        </text>

        {isGenerating() && rateStr() && (
          <text> {rateStr()}</text>
        )}
        {isGenerating() && elapsedStr() && (
          <text> {elapsedStr()}</text>
        )}
      </box>

      {/* ── Row 2: Degradation / compaction (only when active) ── */}
      {showSecondary() && (
        <box height={1}>
          {degradation().active ? (
            <text fg={colors.warning}>
              [{degradation().mode.toUpperCase()}] {degradation().message}
              {degradation().retryCount > 0
                ? ` (${degradation().retryCount}/${degradation().maxRetries})`
                : ""}
            </text>
          ) : compactionProgress()!.percent >= 100 ? (
            <text fg={colors.success}>
              ✓ {compactionProgress()!.message}
            </text>
          ) : (
            <>
              <text fg={colors.primary}>
                ⚙ {compactionProgress()!.message}
              </text>
              <text fg={colors.warning}>
                {" "}
                {"█".repeat(Math.round(compactionProgress()!.percent / 10))}
                {"░".repeat(
                  10 - Math.round(compactionProgress()!.percent / 10),
                )}
              </text>
              <text fg={muted()}> {compactionProgress()!.percent}%</text>
            </>
          )}
        </box>
      )}
    </box>
  )
}

// ts-cli/src/components/StatusLine.tsx
import { memo, useState, useEffect, useRef } from 'react';
import { Box, Text } from 'ink';
import { useAppStatusLine, useAppIsGenerating, useAppDegradation, useAppPdcaPhase, useAppPlanTasks } from '../hooks/useAppState.js';
import { t } from '../theme.js';

function formatTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}K`;
  return String(n);
}

function formatRate(rate: number): string {
  if (rate <= 0) return '';
  if (rate >= 100) return `${Math.round(rate)}t/s`;
  if (rate >= 10) return `${rate.toFixed(1)}t/s`;
  return `${rate.toFixed(1)}t/s`;
}

function formatElapsed(sec: number): string {
  if (sec <= 0) return '';
  if (sec >= 60) {
    const m = Math.floor(sec / 60);
    const s = sec % 60;
    return `${m}m${s}s`;
  }
  return `${sec}s`;
}

export const StatusLine = memo(function StatusLine() {
  const { usage, modelName, planMode, autoMode, connected, statusText, messagesLen,
          tokenRate, compactionProgress } = useAppStatusLine();
  const degradation = useAppDegradation();
  const pdcaPhase = useAppPdcaPhase();
  const planTasks = useAppPlanTasks();
  const msgCount = messagesLen;

  const isGenerating = useAppIsGenerating();
  const startTimeRef = useRef<number>(0);
  const [now, setNow] = useState(Date.now());
  useEffect(() => {
    if (isGenerating) {
      if (startTimeRef.current === 0) startTimeRef.current = Date.now();
      const timer = setInterval(() => setNow(Date.now()), 1000);
      return () => clearInterval(timer);
    } else {
      startTimeRef.current = 0;
    }
  }, [isGenerating]);
  const generationElapsed = isGenerating
    ? Math.floor((now - startTimeRef.current) / 1000)
    : 0;

  const pct = Math.min(100, Math.round(usage.usageRatio * 100));
  const filled = Math.round(pct / 10);
  const bar = '\u2588'.repeat(filled) + '\u2591'.repeat(10 - filled);
  const model = modelName || (connected ? 'ready' : 'connecting...');

  const modeLabel = planMode ? ' Plan ' : ' Act ';
  const modeColor = planMode ? t.plan : t.success;

  const connIcon = connected ? '\u25CF' : '\u25CB';
  const connColor = connected ? t.connected : t.disconnected;

  const isError = statusText.startsWith('Error:');
  const barColor = pct > 90 ? t.error : pct > 70 ? t.warning : t.text;
  const rateStr = formatRate(tokenRate);
  const elapsedStr = formatElapsed(generationElapsed);

  const p = usage.promptTokens;
  const c = usage.completionTokens;

  return (
    <Box flexDirection="column" width="100%" paddingRight={1}>
      <Box height={1}>
        <Text bold color={t.primary}>jwcode</Text>
        <Text>  </Text>
        <Text backgroundColor={modeColor} color="black"> {modeLabel} </Text>
        <Text>  </Text>
        {autoMode && (
          <>
            <Text backgroundColor={t.auto} color="black"> AUTO </Text>
            <Text>  </Text>
          </>
        )}
        {pdcaPhase && (
          <>
            <Text backgroundColor={t.warning} color="black"> {pdcaPhase} </Text>
            <Text>  </Text>
          </>
        )}
        {planTasks.length > 0 && (
          <>
            <Text color={t.primary}>{planTasks.filter(t => t.status === 'completed').length}</Text>
            <Text dimColor>/</Text>
            <Text color={t.text}>{planTasks.length}</Text>
            <Text dimColor> tasks</Text>
            <Text>  </Text>
          </>
        )}
        <Text color={connColor}>{connIcon} </Text>
        <Text color={t.success}>{model}</Text>
        <Text>  </Text>
        <Text dimColor>{msgCount}msgs</Text>

        {p > 0 || c > 0 ? (
          <>
            <Text>  </Text>
            <Text color={t.info}>{formatTokens(p)}</Text>
            <Text dimColor>+</Text>
            <Text color={t.success}>{formatTokens(c)}</Text>
            <Text dimColor>=</Text>
            <Text color={t.warning}>{formatTokens(usage.totalTokens)}</Text>
          </>
        ) : (
          <>
            <Text>  t:</Text>
            <Text color={t.warning}>{formatTokens(usage.totalTokens)}</Text>
          </>
        )}
        <Text>  </Text>
        <Text color={barColor}>{bar} {pct}%</Text>

        {isGenerating && rateStr && (
          <>
            <Text>  </Text>
            <Text color={t.tool}>{rateStr}</Text>
          </>
        )}

        {isGenerating && elapsedStr && (
          <>
            <Text>  </Text>
            <Text color={t.primary}>{elapsedStr}</Text>
          </>
        )}
      </Box>
      {degradation.active && (
        <Box height={1}>
          <Text color={t.warning} dimColor>
            [{degradation.mode.toUpperCase()}] {degradation.message}
            {degradation.retryCount > 0 ? ` (${degradation.retryCount}/${degradation.maxRetries})` : ''}
          </Text>
        </Box>
      )}
      {compactionProgress && (
        <Box height={1}>
          <Text color={compactionProgress.percent >= 100 ? t.success : t.primary}>
            {compactionProgress.percent >= 100 ? '\u2713' : '\u2699'} {compactionProgress.message}
          </Text>
          <Text> </Text>
          <Text color={t.warning}>{'\u2588'.repeat(Math.round(compactionProgress.percent / 10))}{'\u2591'.repeat(10 - Math.round(compactionProgress.percent / 10))}</Text>
          <Text dimColor> {compactionProgress.percent}%</Text>
        </Box>
      )}
      {statusText && statusText !== 'connecting...' && (
        <Box height={1}>
          <Text color={isError ? t.error : t.muted} dimColor={!isError}>
            {statusText.slice(0, 100)}
          </Text>
        </Box>
      )}
    </Box>
  );
});
