// ts-cli/src/solid/components/App.tsx
/**
 * App — root Solid+OpenTUI component.
 * Replaces Ink/React App.tsx. Ties together all providers, components,
 * keyboard handling, @ file references, command execution, and state.
 */
import { createSignal, createMemo, onCleanup, onMount } from "solid-js"
import { useKeyboard, useRenderer, useTerminalDimensions } from "@opentui/solid"
import { MouseButton } from "@opentui/core"
import { useTheme } from "../context/theme"
import * as Clipboard from "../util/clipboard"
import { useAppStateContext } from "../hooks/AppStateProvider"
import { useClient } from "../hooks/ClientProvider"
import { createCommandHandler } from "../hooks/useCommandHandler"
import { wireStreamHandlers } from "../hooks/useStreamHandlers"
import { createApprovalQueue } from "../hooks/useApprovalQueue"
import { TextInput } from "./TextInput"
import { ChatArea } from "./ChatArea"
import { StatusLine } from "./StatusLine"
import { CommandPalette } from "./CommandPalette"
import { FilePalette } from "./FilePalette"
import { SessionPicker, type SessionInfo } from "./SessionPicker"
import { ApprovalModal } from "./ApprovalModal"
import { ConfigPanel } from "./ConfigPanel"
import { PlanTaskBoard } from "./PlanTaskBoard"
import { HELP_TEXT } from "../../commands"
import { createMessage } from "../../protocol"
import { recordMessage } from "../../messageStore"
import { registerDefaults, matchBinding, setActiveContexts, type KeybindingContext, type KeyAction } from "../hooks/useKeybinding"
import { useSelection } from "../hooks/useSelection"
import { ToolPalette } from "./ToolPalette"
import { scanSystemTools } from "../util/toolScanner"
import { loadHistory, saveHistory, dedupPush } from "../util/history"

// ---- Constants ----

const RESERVED_ROWS = 5
const INPUT_HISTORY_MAX = 30

const WELCOME_TIPS = [
  "输入 / 查看命令列表，@ 引用文件",
  "Ctrl+L 清屏 | Ctrl+S 暂停 | Ctrl+N 新建会话 | Ctrl+R 历史会话",
  "F1 查看帮助 | Tab 切换规划/执行模式 | ESC ESC 停止生成",
  "/plan 先规划再执行 | /auto 自动批准工具执行",
  "支持多模型切换: /model <模型名>",
  "支持 @ 文件引用，自动读取文件内容作为上下文",
  "支持 /compact 压缩上下文 | /rewind 撤销到上一步",
]

// ---- Input history (module-level, persisted to ~/.jwcode/history.json) ----
let inputHistory: string[] = loadHistory()
let historyIdx = -1

/** Find last @ not preceded by a word char (to exclude emails). Returns index or -1. */
function findAtTrigger(value: string): number {
  for (let i = value.length - 1; i >= 0; i--) {
    if (value[i] === "@") {
      if (i > 0 && /\w/.test(value[i - 1])) continue
      return i
    }
  }
  return -1
}

interface Props {
  backendUrl: string
  wsUrl: string
  onExit: () => void
}

export function App(props: Props) {
  const { theme } = useTheme()
  const renderer = useRenderer()
  const dims = useTerminalDimensions()
  const terminalCols = () => dims().width
  const terminalRows = () => dims().height

  // ---- App state via store ----
  const {
    state, setState,
    messages, currentMessage, isGenerating, planMode, autoMode,
    connected, statusText,
  } = useAppStateContext()

  // ---- Client ----
  const client = useClient()

  // ---- Session allow ref (shared between approval queue and stream handlers) ----
  const sessionAllowRef = { current: new Set<string>() }

  // ---- Approval queue ----
  const approvalQueue = createApprovalQueue(sessionAllowRef)

  // ---- Wire stream handlers + keybinding defaults ----
  onMount(() => {
    const unsubStream = wireStreamHandlers(client, setState, {
      onApproval: (item) => approvalQueue.addToQueue(item),
      sessionAllowRef,
    })
    const unsubKeys = registerDefaults()
    onCleanup(() => { unsubStream(); unsubKeys() })

    // Scan system tools on startup (async to avoid blocking render)
    setTimeout(() => {
      try {
        const tools = scanSystemTools()
        setSystemTools(tools)
        if (tools.length > 0) {
          setState("statusText", `Loaded ${tools.length} system tools (type ! to use)`)
        }
      } catch { /* ignore scanner failures */ }
    }, 100)
  })

  // ---- UI signals ----
  const [input, setInput] = createSignal("")
  const [showPalette, setShowPalette] = createSignal(false)
  const [showFilePalette, setShowFilePalette] = createSignal(false)
  const [fileQuery, setFileQuery] = createSignal("")
  const [fileList, setFileList] = createSignal<string[]>([])
  const [showHelp, setShowHelp] = createSignal(false)
  const [showCheatsheet, setShowCheatsheet] = createSignal(false)
  const [helpScroll, setHelpScroll] = createSignal(0)
  const [currentTip] = createSignal(Math.floor(Math.random() * WELCOME_TIPS.length))
  const [showSessionPicker, setShowSessionPicker] = createSignal(false)
  const [sessionList, setSessionList] = createSignal<SessionInfo[]>([])

  // ---- Tool palette state ----
  const [showToolPalette, setShowToolPalette] = createSignal(false)
  const [toolQuery, setToolQuery] = createSignal("")
  const [systemTools, setSystemTools] = createSignal<string[]>([])

  // ---- Selection hook (复制由右键处理器完成) ----
  const selection = useSelection(renderer)

  // ---- Derived state ----
  const paletteActive = () => showPalette() || showFilePalette() || showSessionPicker() || showToolPalette()
  const viewportHeight = () => Math.max(3, terminalRows() - RESERVED_ROWS)
  const msgCount = () => messages().length
  const planTasks = () => state.planTasks
  // Rows reserved below text input: border top/bottom (2) + content (1) + char count (1) + StatusLine (1-2)
  const textInputBottomReserved = () => 4 + (state.degradation?.active || state.compactionProgress ? 2 : 1)

  // ---- File debounce ref (module var) ----
  let fileDebounceTimer: ReturnType<typeof setTimeout> | null = null

  // ---- Command execution ----
  // Wrap onExit to send exit signal to backend first
  const handleExit = () => {
    try {
      client.send("exit")
      client.close()
    } catch { /* ignore */ }
    props.onExit()
  }

  const commandHandler = createCommandHandler({
    client,
    planMode,
    setState,
    setInput: (v: string) => setInput(v),
    setShowHelp: (v: boolean) => setShowHelp(v),
    setShowPalette: (v: boolean) => setShowPalette(v),
    onExit: handleExit,
  })

  // ---- @ file reference ----
  async function handleFileSelect(path: string | null) {
    if (path) {
      const atIdx = findAtTrigger(input())
      if (atIdx >= 0) {
        const newValue = input().slice(0, atIdx) + path + " "
        setInput(newValue)
      }
    }
    setShowFilePalette(false)
    setFileQuery("")
    setFileList([])
  }

  function handleToolSelect(tool: string | null) {
    if (tool) {
      // Replace !query in input with selected tool name
      const bangIdx = input().lastIndexOf("!")
      if (bangIdx >= 0) {
        const before = input().slice(0, bangIdx)
        setInput(before + tool + " ")
      } else {
        setInput(tool + " ")
      }
      setShowToolPalette(false)
    } else {
      setShowToolPalette(false)
    }
  }

  function handlePaletteSelect(cmd: string | null) {
    if (cmd) {
      setInput(cmd)
      setShowPalette(false)
    } else {
      setShowPalette(false)
      setInput("")
    }
  }

  async function resolveAndSend(text: string) {
    let finalText = text
    const fileCtxs: string[] = []
    const seenPaths = new Set<string>()

    // Parse @-referenced files and fetch their content
    const atRe = /(?:^|\s)@(\S+)/g
    let match: RegExpExecArray | null
    while ((match = atRe.exec(finalText)) !== null) {
      const raw = match[0]
      const path = match[1].replace(/[^a-zA-Z0-9_\-./\\]/g, "")
      if (path && path.length < 500 && !seenPaths.has(path)) {
        seenPaths.add(path)
        try {
          const content = await client.readFileContent(path)
          if (content != null) {
            const ext = path.includes(".") ? path.split(".").pop() || "" : ""
            fileCtxs.push(`<context ref="${path}">\n\`\`\`${ext}\n${content}\n\`\`\`\n</context>`)
          }
        } catch { /* skip files that can't be read */ }
      }
      // Remove the @reference from the text
      finalText = finalText.replace(raw, "")
    }

    // Prepend contexts before user message
    if (fileCtxs.length > 0) {
      finalText = fileCtxs.join("\n") + "\n" + finalText.trim()
    }

    const msg = createMessage("user", finalText)
    setState((prev) => ({
      ...prev,
      messages: [...prev.messages, msg],
    }))
    recordMessage("user", finalText)
    client.chat(finalText, planMode())
  }

  // ---- ! trigger detection ----
  function findBangTrigger(value: string): number {
    for (let i = value.length - 1; i >= 0; i--) {
      if (value[i] === "!") {
        // Must be at start of input or after whitespace
        if (i === 0 || /\s/.test(value[i - 1])) return i
        continue
      }
    }
    return -1
  }

  // ---- Input change handler ----
  function handleChange(value: string) {
    setInput(value)
    setShowPalette(value.startsWith("/"))

    // Close tool palette if ! is no longer present
    if (showToolPalette()) {
      const bangIdx = findBangTrigger(value)
      if (bangIdx < 0) {
        setShowToolPalette(false)
      } else {
        const q = value.slice(bangIdx + 1)
        setToolQuery(q)
      }
    }

    const atIdx = findAtTrigger(value)
    if (atIdx >= 0) {
      const query = value.slice(atIdx + 1)
      if (/^[\w.\-\\\/\s]*$/.test(query) && query.length < 200) {
        setFileQuery(query)
        setShowFilePalette(true)
        if (fileDebounceTimer) clearTimeout(fileDebounceTimer)
        fileDebounceTimer = setTimeout(async () => {
          try {
            const files = await client.listFiles(query.trim() || undefined)
            setFileList(files)
          } catch { /* ignore */ }
        }, 150)
        return
      }
    }
    setShowFilePalette(false)
    setFileQuery("")

    // Check for ! trigger (system tool palette)
    const bangIdx = findBangTrigger(value)
    if (bangIdx >= 0) {
      const query = value.slice(bangIdx + 1)
      if (query.length < 100) {
        setToolQuery(query)
        setShowToolPalette(true)
        return
      }
    }
    setShowToolPalette(false)
    setToolQuery("")
  }

  // ---- Submit handler ----
  function handleSubmit(value: string) {
    if (showPalette() || showFilePalette() || showToolPalette()) return
    if (!value.trim()) return

    // Save to input history (dedup + cap + persist)
    inputHistory = dedupPush(inputHistory, value)
    if (inputHistory.length > INPUT_HISTORY_MAX) {
      inputHistory = inputHistory.slice(-INPUT_HISTORY_MAX)
    }
    saveHistory(inputHistory)
    historyIdx = -1

    commandHandler(value)
  }

  // ---- Session handlers ----
  async function handleNewSession() {
    setState((prev) => ({
      ...prev,
      messages: [],
      currentMessage: null,
      planTasks: [],
      pdcaPhase: "",
      statusText: "New session started",
    }))
    client.send("create_session")
  }

  async function handleOpenSessionHistory() {
    try {
      const sessions = await client.listSessions()
      setSessionList(sessions)
      setShowSessionPicker(true)
    } catch { /* ignore */ }
  }

  async function handleSessionSelect(session: SessionInfo | null) {
    setShowSessionPicker(false)
    if (!session) return
    try {
      const msgs = await client.getSessionMessages(session.id)
      const mapped = (msgs || []).map((m: any) =>
        createMessage(
          (m.type === "chat" || m.type === "plan") ? "user" : "assistant",
          m.data || m.message || JSON.stringify(m),
        ),
      )
      setState((prev) => ({
        ...prev,
        messages: mapped.length > 0 ? mapped : prev.messages,
        statusText: `Loaded session: ${session.id} (${mapped.length} msgs)`,
      }))
    } catch { /* ignore */ }
  }

  async function handleSessionDelete(sessionId: string) {
    try {
      await client.deleteSession(sessionId)
      const sessions = await client.listSessions()
      setSessionList(sessions)
    } catch { /* ignore */ }
  }

  // ---- Help toggle ----
  function handleToggleHelp() {
    if (showHelp()) {
      setShowHelp(false)
    } else {
      setShowHelp(true)
      setHelpScroll(0)
    }
  }

  // ---- Keyboard shortcuts (global, non-input) ----
  let lastEscTime = 0

  useKeyboard((key: any) => {
    const keyName = key.name ?? ""
    const ctrl = !!key.ctrl

    // Skip when modals are open
    if (showPalette() || showFilePalette() || showSessionPicker() || showToolPalette()) return

    // App-specific overrides (before keybinding dispatch)
    // Ctrl+P: Command palette
    if (ctrl && keyName === "p") {
      setShowPalette((v) => !v)
      return
    }
    // Ctrl+R: Session history
    if (ctrl && keyName === "r") {
      handleOpenSessionHistory()
      return
    }
    // Ctrl+E / Ctrl+O: Toggle tool call expand
    if ((ctrl && keyName === "e") || (ctrl && keyName === "o")) {
      setState("toolCallsExpanded", (v) => !v)
      return
    }
    // ?: Toggle keyboard cheatsheet overlay
    if (keyName === "?" || key.sequence === "?") {
      setShowCheatsheet((v) => !v)
      return
    }
    // Input history: Up/Down
    if (keyName === "up" || keyName === "down") {
      if (inputHistory.length === 0) return
      if (keyName === "up") {
        historyIdx = Math.min(historyIdx + 1, inputHistory.length - 1)
      } else {
        historyIdx = Math.max(historyIdx - 1, -1)
      }
      setInput(historyIdx >= 0 ? inputHistory[inputHistory.length - 1 - historyIdx] : "")
      return
    }

    // Dispatch via keybinding registry for standard actions
    const match = matchBinding(keyName, ctrl, false)
    if (match) {
      switch (match.action) {
        case "help":
          handleToggleHelp()
          break
        case "new-session":
          handleNewSession()
          break
        case "clear":
          setState((prev) => ({
            ...prev,
            messages: [],
            currentMessage: null,
            planTasks: [],
            pdcaPhase: "",
            statusText: "Screen cleared",
          }))
          break
        case "config-panel":
          setState("showConfigPanel", (v: boolean) => !v)
          break
        case "toggle-plan":
          setState((prev) => ({ ...prev, planMode: !prev.planMode, planWaiting: false }))
          break
        case "stop":
          if (showHelp()) { setShowHelp(false); break }
          if (isGenerating()) {
            const now = Date.now()
            const prev = lastEscTime
            lastEscTime = now
            if (prev > 0 && now - prev < 500) {
              client.stop()
              setState("statusText", "Stopped (ESC×2)")
            } else {
              client.pause()
              setState("statusText", "Paused — press ESC again to stop")
            }
          }
          break
        case "pause":
          client.pause()
          setState("statusText", "Paused. Press again to resume.")
          break
        case "toggle-auto":
          setState((prev) => ({ ...prev, autoMode: !prev.autoMode }))
          break
        // ── Scroll actions ──
        case "scroll-up":
          setState("scrollOffset", (prev: number) => prev + 1)
          break
        case "scroll-down":
          setState("scrollOffset", (prev: number) => Math.max(0, prev - 1))
          break
        case "page-up":
          setState("scrollOffset", (prev: number) => prev + 5)
          break
        case "page-down":
          setState("scrollOffset", (prev: number) => Math.max(0, prev - 5))
          break
        case "scroll-top":
          // Scroll to top: set a very large offset (clamped in ChatArea)
          setState("scrollOffset", 99999)
          break
        case "scroll-bottom":
          setState("scrollOffset", 0)
          break
      }
    }
  })

  // ---- Render ----

  // Welcome screen
  const showWelcome = () => msgCount() === 0 && !isGenerating() && !!state.modelName

  // Help text lines
  const helpLines = createMemo(() => HELP_TEXT.split("\n"))
  const helpMax = () => Math.max(5, Math.min(terminalRows() - 12, 10))
  const helpEnd = () => Math.max(0, helpLines().length - helpScroll())
  const helpStart = () => Math.max(0, helpEnd() - helpMax())
  const visibleHelp = () => helpLines().slice(helpStart(), helpEnd())

  // Cheatsheet: grouped by category. Pressing ? toggles the overlay.
  const CHEATSHEET: Array<[string, string, "Global" | "Session" | "Input" | "View" | "Help"]> = [
    ["Ctrl+L", "清屏", "Global"],
    ["Ctrl+S", "暂停/继续", "Global"],
    ["Ctrl+N", "新建会话", "Session"],
    ["Ctrl+R", "会话历史", "Session"],
    ["Ctrl+P", "命令面板", "Input"],
    ["Tab", "切换规划/执行", "Input"],
    ["@", "引用文件", "Input"],
    ["!", "系统工具", "Input"],
    ["↑ / ↓", "浏览历史", "Input"],
    ["Ctrl+E", "展开工具调用", "View"],
    ["PgUp/PgDn", "滚动消息", "View"],
    ["?", "本速查", "Help"],
    ["Esc Esc", "停止生成", "Global"],
  ]
  const groupColor = (g: string): string => {
    const t2 = theme as any
    if (g === "Input") return t2.primary
    if (g === "Session") return t2.success
    if (g === "View") return t2.info
    if (g === "Help") return t2.warning
    return t2.text
  }

  return (
    <box flexDirection="column" width="100%"
      onMouseDown={(evt: any) => {
        if (evt.button === MouseButton.RIGHT) {
          const sel = renderer.getSelection()
          const text = sel ? sel.getSelectedText() : ""
          if (text) {
            Clipboard.copy(text).catch(() => {})
            setState("statusText", "Copied " + text.length + " chars")
            renderer.clearSelection?.()
          } else {
            // 无选区 → 尝试粘贴剪贴板文本
            Clipboard.readText().then(pasted => {
              if (pasted) {
                setInput(v => v + pasted)
                setState("statusText", "Pasted " + pasted.length + " chars")
              }
            }).catch(() => {})
          }
          return
        }
        selection.handleMouseDown(evt)
      }}
      onMouseMove={selection.handleMouseMove}
      onMouseUp={selection.handleMouseUp}
    >
      {connected() ? (
        <box flexDirection="column">
          {/* Welcome message — two-column layout with vertical divider */}
          {showWelcome() && (
            <box borderStyle="single" border={true} borderColor={theme.primary} flexDirection="column" marginBottom={1}>
              <box flexDirection="row">
                {/* Left column: version, model, workspace */}
                <box flexDirection="column" width="50%" paddingX={1}>
                  <box>
                    <text attributes={1} fg={theme.primary}>{">_ JWCode v3.0.0"}</text>
                  </box>
                  <box>
                    <text fg={theme.textMuted}>  模型: </text>
                    <text fg={theme.success}>{state.modelName || "connecting..."}</text>
                    <text fg={theme.textMuted}>  /model 切换</text>
                  </box>
                  <box>
                    <text fg={theme.textMuted}>  目录: </text>
                    <text fg={theme.warning}>{process.cwd()}</text>
                  </box>
                </box>
                {/* Vertical divider */}
                <text fg={theme.border}>│</text>
                {/* Right column: tips and commands */}
                <box flexDirection="column" width="50%" paddingX={1}>
                  <box>
                    <text attributes={1} fg={theme.primary}>Quick Commands</text>
                  </box>
                  <box>
                    <text fg={theme.info}>  /plan 先规划再执行  /auto 自动批准  PgUp/PgDn 滚动</text>
                  </box>
                  <box>
                    <text fg={theme.textMuted}>  Tips: </text>
                    <text fg={theme.info}>{WELCOME_TIPS[currentTip()]}</text>
                  </box>
                </box>
              </box>
            </box>
          )}

          {/* Chat area */}
          <box flexGrow={paletteActive() ? 0 : 1} flexDirection="column">
            <ChatArea
              terminalCols={terminalCols()}
              terminalRows={terminalRows()}
            />
          </box>

          {/* Plan task board (if plan tasks exist) */}
          {planTasks().length > 0 && (
            <PlanTaskBoard tasks={planTasks()} terminalCols={terminalCols()} />
          )}

          {/* Input box — bordered area */}
          <box
            borderStyle="round"
            borderColor={theme.border}
            backgroundColor={theme.inputBackground}
            flexDirection="column"
            marginTop={1}
            marginX={1}
          >
            <box paddingLeft={1}>
              <text fg={theme.success} attributes={1}>{"> "}</text>
              <TextInput
                value={input()}
                onChange={handleChange}
                onSubmit={handleSubmit}
                placeholder="Type a message or / for commands..."
                disabled={approvalQueue.currentApproval !== null}
                bottomReserved={textInputBottomReserved()}
              />
            </box>
          </box>

          {/* Init progress */}
          {state.initProgress && state.initProgress.percent < 100 && (
            <box paddingX={1} height={1}>
              <text fg={theme.warning}>{state.initProgress.message}</text>
            </box>
          )}
          {state.initProgress?.stage === "complete" && (
            <box paddingX={1} height={1}>
              <text fg={theme.success}>✓ {state.initProgress.message}</text>
            </box>
          )}
          {state.initProgress?.stage === "error" && (
            <box paddingX={1} height={1}>
              <text fg={theme.error}>✗ {state.initProgress.message}</text>
            </box>
          )}

          {/* Palettes / modals */}
          <box flexDirection="column">
            {showPalette() && (
              <CommandPalette filter={input()} onSelect={handlePaletteSelect} />
            )}
            {showFilePalette() && (
              <FilePalette query={fileQuery()} files={fileList()} onSelect={handleFileSelect} />
            )}
            {showSessionPicker() && (
              <SessionPicker
                sessions={sessionList()}
                onSelect={handleSessionSelect}
                onDelete={handleSessionDelete}
              />
            )}
            {showToolPalette() && (
              <ToolPalette tools={systemTools()} filter={toolQuery()} onSelect={handleToolSelect} />
            )}
            {showHelp() && (
              <box borderStyle="single" border={true} borderColor={theme.primary} flexDirection="column" paddingX={1}>
                {helpLines().length > helpMax() && (
                  <box>
                    <text fg={theme.textMuted}>
                      {"  " + (helpStart() + 1) + "-" + helpEnd() + " / " + helpLines().length + "  PgUp/PgDn scroll / Esc close"}
                    </text>
                  </box>
                )}
                {visibleHelp().map((line, i) => (
                  <text fg={theme.primary}>{line}</text>
                ))}
              </box>
            )}
            {showCheatsheet() && (
              <box borderStyle="round" border={true} borderColor={theme.warning} flexDirection="column" paddingX={1}>
                <box marginBottom={1}>
                  <text fg={theme.warning} attributes={1}>Keyboard Shortcuts</text>
                  <text fg={theme.textMuted}>  (press ? to close)</text>
                </box>
                {CHEATSHEET.map(([key2, desc, group]) => (
                  <box>
                    <text fg={groupColor(group)}>{group.padEnd(8)}</text>
                    <text fg={theme.textMuted}>  {key2.padEnd(12)}</text>
                    <text fg={theme.text}>{desc}</text>
                  </box>
                ))}
              </box>
            )}
            {state.showConfigPanel && (
              <ConfigPanel onClose={() => setState("showConfigPanel", false)} />
            )}
            {approvalQueue.currentApproval && (
              <ApprovalModal
                toolName={approvalQueue.currentApproval.toolName}
                payload={approvalQueue.currentApproval.payload}
                onAllow={() => approvalQueue.approveCurrent()}
                onDeny={() => approvalQueue.denyCurrent()}
                onAllowSession={() => approvalQueue.allowSession()}
                onAutoMode={() => setState("autoMode", true)}
                queuePosition={{ current: 1, total: approvalQueue.queue.length }}
              />
            )}
          </box>
        </box>
      ) : (
        <box flexDirection="column">
          <box flexGrow={1} flexDirection="column">
            <ChatArea terminalCols={terminalCols()} terminalRows={terminalRows()} />
          </box>
          <box
            borderStyle="round"
            borderColor={theme.border}
            backgroundColor={theme.inputBackground}
            paddingLeft={1}
            marginX={1}
          >
            <text fg={theme.textMuted}>Connecting...</text>
          </box>
        </box>
      )}

      {/* Status line */}
      <StatusLine
        selectionActive={selection.selection().active}
        selectionChars={selection.selection().text.length}
        selectedText={selection.selection().text}
      />

      {/* Disconnected warning */}
      {!connected() && (
        <box height={1}>
          <text fg={theme.error}>Backend not connected -- WebSocket reconnecting.</text>
        </box>
      )}

      {/* Plan waiting confirm */}
      {state.planWaiting && (
        <box height={1}>
          <text fg={theme.warning} attributes={1}>Plan ready -- /confirm to execute, /cancel to discard.</text>
        </box>
      )}
    </box>
  )
}

// ts-cli/src/App.tsx
﻿/**
 * Root Ink component -- layout, WS connection, and event dispatch.
 */
import { useState, useEffect, useRef, useCallback } from 'react';
import { Box, Text, useStdout } from 'ink';
import { TextInput } from './components/TextInput.js';
import { t } from './theme.js';
import { JwCodeClient } from './client.js';
import { StatusLine } from './components/StatusLine.js';
import { debugLog } from './client.js';
import { ChatArea } from './components/ChatArea.js';
import { CommandPalette } from './components/CommandPalette.js';
import { FilePalette } from './components/FilePalette.js';
import { SessionPicker, type SessionInfo } from './components/SessionPicker.js';
import { ApprovalModal } from './components/ApprovalModal.js';
import { updateAppState, useAppSlice, getStore } from './hooks/useAppState.js';
import { createMessage } from './protocol.js';
import { SLASH_COMMANDS, HELP_TEXT } from './commands/index.js';
import { useStreamHandlers } from './hooks/useStreamHandlers.js';
import { useKeyboardInput } from './hooks/useKeyboardInput.js';
import { setClient } from './hooks/useWebSocket.js';

interface AppProps {
  backendUrl: string;
  wsUrl: string;
  onExit: () => void;
}

/** Find last @ not preceded by a word char (to exclude emails). Returns index or -1. */
function findAtTrigger(value: string): number {
  for (let i = value.length - 1; i >= 0; i--) {
    if (value[i] === '@') {
      if (i > 0 && /\w/.test(value[i - 1])) continue; // email part, skip
      return i;
    }
  }
  return -1;
}

export function App({ backendUrl, wsUrl, onExit }: AppProps) {
  const [input, setInput] = useState('');
  const [showPalette, setShowPalette] = useState(false);
  // @ file reference state
  const [showFilePalette, setShowFilePalette] = useState(false);
  const [fileQuery, setFileQuery] = useState('');
  const [fileList, setFileList] = useState<string[]>([]);
  const fileDebounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const referencedFilesRef = useRef<string[]>([]);
  const [showHelp, setShowHelp] = useState(false);
  const [helpScroll, setHelpScroll] = useState(0);
  const [approvalQueue, setApprovalQueue] = useState<Array<{
    approvalId: string;
    toolName: string;
    payload: string;
  }>>([]);
  const currentApproval = approvalQueue.length > 0 ? approvalQueue[0] : null;
  const sessionAllowRef = useRef<Set<string>>(new Set());

  const clientRef = useRef<JwCodeClient | null>(null);
  const { stdout } = useStdout();
  // Terminal size needs to be React state so the tree re-renders on resize
  // (Ink's `stdout.on('resize')` does not bump React state on its own).
  const [terminalRows, setTerminalRows] = useState<number>((stdout as any)?.rows || 24);
  const [terminalCols, setTerminalCols] = useState<number>((stdout as any)?.columns || 80);
  useEffect(() => {
    const onResize = () => {
      setTerminalRows((stdout as any)?.rows || 24);
      setTerminalCols((stdout as any)?.columns || 80);
    };
    (stdout as any)?.on?.('resize', onResize);
    return () => { (stdout as any)?.off?.('resize', onResize); };
  }, [stdout]);

  // Rows reserved by status line, prompt box, borders. ChatArea subtracts
  // this from terminalRows to compute its own viewportHeight.
  const RESERVED_ROWS = 6;

  const connected = useAppSlice(s => s.connected);
  const planWaiting = useAppSlice(s => s.planWaiting);
  const isGenerating = useAppSlice(s => s.currentMessage !== null);
  const messagesLen = useAppSlice(s => s.messages.length);
  const modelName = useAppSlice(s => s.modelName);
  const planMode = useAppSlice(s => s.planMode);
  // Session history state
  const [showSessionPicker, setShowSessionPicker] = useState(false);
  const [sessionList, setSessionList] = useState<SessionInfo[]>([]);

  const [layoutVer, setLayoutVer] = useState(0);
  // Increment layout version when layout-affecting state changes to force full remount
  const prevKey = useRef("");
  useEffect(() => {
    const key = planMode + "-" + connected + "-" + (messagesLen === 0);
    if (prevKey.current && prevKey.current !== key) {
      setLayoutVer(v => v + 1);
    }
    prevKey.current = key;
  }, [planMode, connected, messagesLen]);

  const wireHandlers = useStreamHandlers(setApprovalQueue, sessionAllowRef);

  useEffect(() => {
    const client = new JwCodeClient(backendUrl, wsUrl);
    clientRef.current = client;
    setClient(client);
    wireHandlers(client);

    client.connect().then(async () => {
      try {
        const r = await fetch(backendUrl + '/api/models');
        const d = await r.json();
        const models = (d as any).data?.models;
        const name = models?.[0]?.name || '';
        updateAppState(s => ({ ...s, connected: true, modelName: name }));
      } catch {
        updateAppState(s => ({ ...s, connected: true }));
      }
    }).catch((err: Error) => {
      updateAppState(s => ({ ...s, statusText: 'Connection failed: ' + err.message }));
    });

    return () => { client.close(); };
  }, [backendUrl, wsUrl, wireHandlers]);

  const executeCommand = useCallback((value: string) => {
    const text = value.trim();
    if (!text || !clientRef.current) return;
    setInput('');
    setShowHelp(false);
    setShowPalette(false);

    const parts = text.startsWith('/') ? text.split(/\s+/) : [];
    const cmd = parts[0] || null;
    const cmdArg = parts.slice(1).join(' ');

    if (cmd && cmd in SLASH_COMMANDS) {
      const def = (SLASH_COMMANDS as Record<string, { action: string; needsArg?: boolean } | null>)[cmd];
      if (def === null) {
        setShowHelp(true);
        setHelpScroll(0);
        return;
      }
      const { action, needsArg } = def;
      const cl = clientRef.current;
      switch (action) {
        case '__exit__': onExit(); return;
        case '__confirm_plan':
          updateAppState(prev => {
            if (!prev.planWaiting) return prev;
            cl?.planConfirm();
            return { ...prev, planWaiting: false };
          });
          return;
        case '__cancel_plan': updateAppState(prev => ({ ...prev, planWaiting: false })); return;
        case 'plan_mode': updateAppState(prev => ({ ...prev, planMode: !prev.planMode })); return;
        case 'auto_mode': debugLog('app', 'auto_mode toggle'); updateAppState(prev => ({ ...prev, autoMode: !prev.autoMode })); return;
        case 'clear': updateAppState(prev => ({ ...prev, messages: [], currentMessage: null, contentHeight: 0, scrollOffset: 0 })); return;
        case 'model_change': if (needsArg && cmdArg) cl?.switchModel(cmdArg); return;
        case 'show_context':
          updateAppState(prev => ({
            ...prev,
            statusText: 'Messages: ' + prev.messages.length + ' | Plan: ' + (prev.planMode ? 'On' : 'Off') + ' | Model: ' + (prev.modelName || 'N/A'),
          }));
          return;
        case 'stop': cl?.stop(); return;
        case 'pause': cl?.pause(); return;
        case 'resume': cl?.resume(); return;
        case 'doctor': cl?.doctor(); return;
        case 'rewind': cl?.rewind(); return;
        case 'compact': cl?.compact(); return;
        case 'init': cl?.init(); return;
        case 'effort': if (cmdArg) cl?.effort(cmdArg); return;
        case 'branch': if (cmdArg) cl?.branch(cmdArg); return;
        case 'mcp': if (cmdArg) cl?.mcp(cmdArg); return;
        case 'skills': cl?.skills(); return;
        case 'agents': cl?.agents(); return;
        case 'config': if (cmdArg) cl?.config(cmdArg); return;
        case 'plugin': if (cmdArg) cl?.plugin(cmdArg); return;
        case 'tokens': cl?.send('tokens'); return;
        case 'memory': cl?.send('memory'); return;
        case 'export': if (cmdArg) cl?.send('export', undefined, { path: cmdArg }); return;
        case 'checkpoint': cl?.send('checkpoint'); return;
        case 'test': cl?.send('test'); return;
        case 'lint': cl?.send('lint'); return;
        case 'search': if (cmdArg) cl?.send('search', undefined, { query: cmdArg }); return;
        case 'project': cl?.send('project'); return;
      }
      return;
    }

    if (text.startsWith('/') && !(cmd && cmd in SLASH_COMMANDS)) return;
    // Resolve @ file references
    resolveAndSend(text);
  }, [onExit]);

  // Resolve @-referenced file contents and send message
  const resolveAndSend = useCallback(async (text: string) => {
    const cl = clientRef.current;
    if (!cl) return;

    let finalText = text;
    const files = referencedFilesRef.current;
    referencedFilesRef.current = [];

    const fileCtxs: string[] = [];
    for (const filePath of files) {
      try {
        const content = await cl.readFileContent(filePath);
        if (content) {
          // Remove the raw path reference from the message
          finalText = finalText.replace(filePath, '').trim();
          const ext = filePath.split('.').pop() || '';
          fileCtxs.push(
            `<context ref="${filePath}">\n\`\`\`${ext}\n${content}\n\`\`\`\n</context>`
          );
        }
      } catch { /* file not readable, leave path in text */ }
    }
    if (fileCtxs.length > 0) {
      finalText = fileCtxs.join('\n\n') + '\n\n' + finalText.trim();
      finalText = finalText.trim();
    }

    const msg = createMessage('user', finalText);
    updateAppState(prev => ({ ...prev, messages: [...prev.messages, msg] }));
    // Read planMode from store at send time to avoid re-subscribing in App
    cl.chat(finalText, getStore().getState().planMode);
  }, []);

  const handleSubmit = useCallback((value: string) => {
    if (showPalette || showFilePalette) return;
    executeCommand(value);
  }, [executeCommand, showPalette, showFilePalette]);

  const handleChange = useCallback((value: string) => {
    setInput(value);
    setShowPalette(value.startsWith('/'));

    // @ file reference detection: find last @ not preceded by word char
    const atIdx = findAtTrigger(value);
    if (atIdx >= 0) {
      const query = value.slice(atIdx + 1);
      // Only trigger if query looks like a file path
      if (/^[\w.\-\\\/\s]*$/.test(query) && query.length < 200) {
        setFileQuery(query);
        setShowFilePalette(true);
        // Debounced file fetch
        if (fileDebounceRef.current) clearTimeout(fileDebounceRef.current);
        fileDebounceRef.current = setTimeout(async () => {
          const cl = clientRef.current;
          if (cl) {
            const files = await cl.listFiles(query.trim() || undefined);
            setFileList(files);
          }
        }, 150);
        return;
      }
    }
    // Close file palette when no valid @ trigger
    setShowFilePalette(false);
    setFileQuery('');
    
  }, []);

  const handleFileSelect = useCallback((path: string | null) => {
    if (path) {
      // Replace @query with file path
      const atIdx = findAtTrigger(input);
      if (atIdx >= 0) {
        const newValue = input.slice(0, atIdx) + path + ' ';
        setInput(newValue);
        referencedFilesRef.current.push(path);
      }
    }
    setShowFilePalette(false);
    setFileQuery('');
    setFileList([]);
  }, [input]);

  const handlePaletteSelect = useCallback((cmd: string | null) => {
    if (cmd) { setInput(cmd); setShowPalette(false); }
    else { setShowPalette(false); setInput(''); }
  }, []);

  const shiftApprovalQueue = useCallback(() => {
    setApprovalQueue(prev => prev.length > 1 ? prev.slice(1) : []);
  }, []);

  const handleApprovalAllow = useCallback((approvalId: string) => {
    clientRef.current?.approveHook(approvalId);
    shiftApprovalQueue();
  }, [shiftApprovalQueue]);

  const handleApprovalDeny = useCallback((approvalId: string) => {
    clientRef.current?.denyHook(approvalId);
    shiftApprovalQueue();
  }, [shiftApprovalQueue]);

  const paletteActive = showPalette || showFilePalette || showSessionPicker;

  // Session history handlers
  const handleNewSession = useCallback(() => {
    updateAppState(prev => ({
      ...prev,
      messages: [],
      currentMessage: null,
      scrollOffset: 0,
      contentHeight: 0,
      statusText: 'New session started',
    }));
    // Re-create session on backend
    if (clientRef.current) {
      clientRef.current.send('create_session');
    }
  }, []);

  const handleOpenSessionHistory = useCallback(async () => {
    if (clientRef.current) {
      const sessions = await clientRef.current.listSessions();
      setSessionList(sessions);
      setShowSessionPicker(true);
    }
  }, []);

  const handleSessionSelect = useCallback(async (session: SessionInfo | null) => {
    setShowSessionPicker(false);
    if (!session || !clientRef.current) return;
    const msgs = await clientRef.current.getSessionMessages(session.id);
    const messages: import('./protocol.js').Message[] = msgs.map((m: any) =>
      createMessage(
        (m.type === 'chat' || m.type === 'plan') ? 'user' : 'assistant',
        m.data || m.message || JSON.stringify(m),
      ),
    );
    updateAppState(prev => ({
      ...prev,
      messages: messages.length > 0 ? messages : prev.messages,
      scrollOffset: 0,
      contentHeight: 0,
      statusText: `Loaded session: ${session.id} (${messages.length} msgs)`,
    }));
  }, []);

  const handleSessionDelete = useCallback(async (sessionId: string) => {
    if (clientRef.current) {
      await clientRef.current.deleteSession(sessionId);
      const sessions = await clientRef.current.listSessions();
      setSessionList(sessions);
    }
  }, []);

  const handleToggleHelp = () => {
    if (showHelp) {
      setShowHelp(false);
    } else {
      setShowHelp(true);
      setHelpScroll(0);
    }
  };
  useKeyboardInput({
    showApproval: currentApproval !== null,
    showHelp,
    isGenerating,
    terminalRows,
    viewportHeight: Math.max(3, terminalRows - RESERVED_ROWS),
    paletteOpen: paletteActive,
    clientRef: clientRef as React.MutableRefObject<JwCodeClient | null>,
    onDenyApproval: () => { if (currentApproval) handleApprovalDeny(currentApproval.approvalId); },
    onCloseHelp: () => setShowHelp(false),
    setHelpScroll,
    onToggleHelp: handleToggleHelp,
    onNewSession: handleNewSession,
    onSessionHistory: handleOpenSessionHistory,
  });

  const handleApprovalAllowForModal = useCallback(() => {
    if (currentApproval) handleApprovalAllow(currentApproval.approvalId);
  }, [currentApproval, handleApprovalAllow]);

  const handleApprovalDenyForModal = useCallback(() => {
    if (currentApproval) handleApprovalDeny(currentApproval.approvalId);
  }, [currentApproval, handleApprovalDeny]);

  const handleAllowSession = useCallback(() => {
    if (currentApproval) {
      sessionAllowRef.current.add(currentApproval.toolName);
      handleApprovalAllow(currentApproval.approvalId);
    }
  }, [currentApproval, handleApprovalAllow]);

  const handleAutoMode = useCallback(() => {
    debugLog('app', 'autoMode button pressed');
    updateAppState(prev => ({ ...prev, autoMode: true }));
    if (currentApproval) handleApprovalAllow(currentApproval.approvalId);
  }, [currentApproval, handleApprovalAllow]);

  const placeholder = 'Type a message or / for commands...';

  return (
    <Box key={layoutVer} flexDirection="column" width="100%">
      {connected ? (
        <Box flexDirection="column">
          {messagesLen === 0 && !isGenerating && !!modelName && (
            <Box key="welcome" flexDirection="column" flexShrink={0} marginBottom={1}>
              <Box flexDirection="column" paddingX={1}>
                <Box>
                  <Text color={t.primary} bold>&gt;_ JWCode v3.0.0</Text>
                </Box>
                <Box>
                  <Text dimColor>model:     </Text>
                  <Text color={t.success}>{modelName || 'connecting...'}</Text>
                  <Text dimColor>   /model to change</Text>
                </Box>
                <Box>
                  <Text dimColor>directory: </Text>
                  <Text color={t.warning}>{process.cwd()}</Text>
                </Box>
              </Box>
              <Box paddingLeft={3}>
                <Text dimColor>Tip: Type / for commands, @ to reference files</Text>
              </Box>
              <Box paddingLeft={3}>
                <Text dimColor>TUI shortcuts: F1 help | Ctrl+L clear | Ctrl+S pause | Ctrl+N new | Ctrl+R history | Tab mode | PgUp/PgDn scroll</Text>
              </Box>
            </Box>
          )}
          {/* flexGrow=0 when palette open: prevents Yoga layout overflow + Ink ghost content duplication */}
          <Box flexGrow={paletteActive ? 0 : 1} flexDirection="column">
            <ChatArea
              terminalCols={terminalCols}
              terminalRows={terminalRows}
            />
          </Box>
          <Box flexDirection="row" borderStyle="single" borderColor={t.primary} paddingLeft={1}>
            <Text color={t.success} bold>&gt; </Text>
            <TextInput
              value={input}
              onChange={handleChange}
              onSubmit={handleSubmit}
              placeholder={placeholder}
              disabled={currentApproval !== null}
            />
          </Box>
          {/* flexDirection=column required: Ink 5 defaults to row, which miscalculates overlay heights */}
          <Box flexDirection="column">
            {showPalette && (
              <CommandPalette key="command-palette" filter={input} onSelect={handlePaletteSelect} />
            )}
            {showFilePalette && (
              <FilePalette key="file-palette" query={fileQuery} files={fileList} onSelect={handleFileSelect} />
            )}
            {showSessionPicker && (
              <SessionPicker
                key="session-picker"
                sessions={sessionList}
                onSelect={handleSessionSelect}
                onDelete={handleSessionDelete}
              />
            )}
            {showHelp && (() => {
              const helpLines = HELP_TEXT.split('\\n');
              const helpMax = Math.max(5, Math.min(terminalRows - 12, 10));
              const helpEnd = Math.max(0, helpLines.length - helpScroll);
              const helpStart = Math.max(0, helpEnd - helpMax);
              const visibleHelp = helpLines.slice(helpStart, helpEnd);
              return (
                <Box key="help-box" flexDirection="column" borderStyle="single" borderColor={t.primary} paddingX={1}>
                  {helpLines.length > helpMax && (
                    <Box>
                      <Text dimColor>{'  ' + (helpStart + 1) + '-' + helpEnd + ' / ' + helpLines.length + '  PgUp/PgDn scroll / Esc close'}</Text>
                    </Box>
                  )}
                  {visibleHelp.map((line, i) => (
                    <Text key={i} color={t.primary}>{line}</Text>
                  ))}
                </Box>
              );
            })()}
            {currentApproval && (
              <ApprovalModal
                key="approval-modal"
                toolName={currentApproval.toolName}
                payload={currentApproval.payload}
                onAllow={handleApprovalAllowForModal}
                onDeny={handleApprovalDenyForModal}
                onAllowSession={handleAllowSession}
                onAutoMode={handleAutoMode}
                queuePosition={{ current: 1, total: approvalQueue.length }}
                />
              )}
          </Box>
        </Box>
      ) : (
        <Box flexDirection="column">
          <Box flexGrow={1} flexDirection="column">
            <ChatArea
              terminalCols={terminalCols}
              terminalRows={terminalRows}
            />
          </Box>
          <Box paddingLeft={1}>
            <Text dimColor>Connecting...</Text>
          </Box>
        </Box>
      )}
      <StatusLine key={planMode ? 'status-plan' : 'status-act'} />
      {!connected && (
        <Box height={1}>
          <Text color={t.error}>Backend not connected -- WebSocket reconnecting.</Text>
        </Box>
      )}
      {planWaiting && (
        <Box height={1}>
          <Text color={t.warning} bold>Plan ready -- /confirm to execute, /cancel to discard.</Text>
        </Box>
      )}
    </Box>
  );
}
